### ISSUE TITLE
Type signature confusion, too many strings

### ISSUE THREAD

**Issue by Rembane** [ianbollinger/purescript-web-storage#5]
Good morning,

I become confused when I read the documentation on [Pursuit](https://pursuit.purescript.org/packages/purescript-web-storage/2.0.0/docs/Web.Storage.Storage), since many of the parameters to the functions are strings. 

I have two proposed solutions to my confusion:

- Either: add type aliases for the key and value parameters
- Or: add a description for each relevant function that describes what each parameter does.

I can make a pull request if you think this is a good idea.

What do you think?

**Comment by chexxor** [comment]
I think docs would be a good first step. Personally, I prefer to reserve the use of type aliases to simplify references to a type which is a composition of many other types.

I wonder what the docs would be like?

`getItem :: String -> Storage -> Effect (Maybe String)`

Here, the argument is the "key" of the data item to retrieve, and the resulting type is the data item. I think this function is pretty intuitive, though docs describing this would still be helpful.

`setItem :: String -> String -> Storage -> Effect Unit`

Here, the type signature doesn't really help, so inline docs would be really helpful.

Introducing a newtype *would* help the type signature, but I'm not sure it's a good change, simply because of the performance cost.

```
newtype Key = Key String
newtype Value = Value String
-- Using the `setItem` function, then, would require two additional operations for every use:
--   `Key :: String -> Key`
--   `Value:: String -> Value`
setItem :: Key -> Value -> Storage -> Effect Unit
```

 If this was my personal library, I'd make a "most typesafe" module, which has these newtypes, and a "most efficient" module, which doesn't. (or just put both functions in one module, `getItem` and `getItem'`) I'm sure other people would disagree with that, though. It's cases like this where a library or library ecosystem having explicitly defined design values would help resolve questions like this.

So, I think inline function docs are the easiest, least controversial solution here. (but I'd also welcome a library design discussion. :) )

**Comment by hdgarrood** [comment]
Since these repos are meant to contain ‘low level’ apis which mirror the actual web apis as closely as possible, I think keeping keys and values as just strings is probably appropriate. I’d prefer not to add a ‘more typesafe’ variant in the same library - I think library size is a big factor in how easy it is to get your head around - and it’s very easy to do that locally to your own project if that’s what you want anyway.

The docs in #7 are a good first step but I think what would really solve this issue once and for all would be to add some basic examples to the docs.

**Comment by Rembane** [comment]
The docs in #7 removes my confusion and solves my problem. 

Here's an example I threw together, I don't really know if it's useful yet though.

Do you want one example per function or a big usage example at the top of the module?

```purescript
module Main where

import Prelude
import Effect (Effect)
import Effect.Console (log, logShow)
import Web.HTML (window)
import Web.HTML.Window (localStorage)
import Web.Storage.Storage (clear, getItem, removeItem, setItem)

main :: Effect Unit
main = do
  w <- window
  s <- localStorage w
  setItem "this-is-my-key" "Here is my value." s
  v <- getItem "this-is-my-key" s
  logShow v

  removeItem "this-is-my-key" s
  v' <- getItem "this-is-my-key" s
  log "It is gone!"
  logShow v'

  clear s
```

**Comment by chexxor** [comment]
LGTM. I think it can just be added to the module docs.

```
-- | This module defines a data type and various functions for interacting
-- | with the `Storage` interface of the Web Storage API.
-- | For example:
-- |
-- | ```purescript
-- | main :: Effect Unit
-- | main = do
-- |   w <- window
-- |   s <- localStorage w
-- |   setItem "this-is-my-key" "Here is my value." s
-- |   v <- getItem "this-is-my-key" s
-- |   logShow v
-- | 
-- |   removeItem "this-is-my-key" s
-- |   v' <- getItem "this-is-my-key" s
-- |   log "It is gone!"
-- |   logShow v'
-- | 
-- |   clear s
-- | ```
module Web.Storage.Storage
  ( Storage
  , length
...
```

I'll make a PR in a week or two if @Rembane doesn't have time.

**Comment by hdgarrood** [comment]
I agree, I think a single example is probably clearest in this instance. Also best to keep the imports, I think.
